apiVersion: argoproj.io/v2alpha1
kind: Workflow
metadata:
  generateName: salmon-dna443
spec:
  # run the salmon algorithm as TSP with DNA 178
  entrypoint: salmon
  arguments:
    parameters:
    - name: iterations
      value: 30
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: salmon-volume
  templates:
  - name: salmon
    steps:
    - - name: seed
        template: gen-random-seed
    - - name: run
        template: salmon-dna443
        arguments:
          parameters:
          - name: rand-seed
            value: "{{item}}"
        withParam: "{{steps.seed.outputs.result}}"
    - - name: process
        template: process-results
        arguments:
          parameters:
          - name: rand-seed
            value: "{{steps.seed.outputs.result}}"
    - - name: print
        template: print-output

  - name: gen-random-seed
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random, os, glob
        for filename in glob.glob('/mnt/vol/*-dna443.txt'):
            os.remove(filename)
        print(random.sample(range(1,100), {{workflow.parameters.iterations}}))

  - name: salmon-dna443
    inputs:
      parameters:
      - name: rand-seed
    container:
      image: quay.io/onyiny_ang/salmon-tsp:dna443-latest
      command: [sh, -xc]
      args:
      - |
        R='{{inputs.parameters.rand-seed}}';
        echo $R > /SalmonTSP/randomseed.txt
        cd /SalmonTSP
        ./Salmon | tee -a /mnt/vol/$R-dna443
        mv salmon1.txt /mnt/vol/$R-dna443.txt
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

  - name: process-results
    inputs:
      parameters:
      - name: rand-seed
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        import sys
        import os
        from shutil import copyfile

        path = '/mnt/vol/'
        os.chdir(path)
        best = -1.0
        seedtrack = ""
        total = 0
        for r in {{inputs.parameters.rand-seed}}:
          filename = str(r)+"-dna443.txt"
          try:
            with open(filename) as f:
              value = float(f.readline().split().pop())
              if value > best:
                best = value
                seedtrack = str(r)
              total+=value
          except:
            print("Failed to open "+str(r)+"-dna443.txt")
        average = total/(len({{inputs.parameters.rand-seed}}))
        copyfile(seedtrack+"-dna443.txt", "result-dna443.txt")
        with open('result-dna443.txt', 'a') as g:
          g.write("\nThe average of best paths found in 30 runs was: "+str(average)+"\n The seeds used were: "+str({{inputs.parameters.rand-seed}}))
          g.close()
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

  - name: print-output
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /mnt/vol/result-dna443.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

